# fly.toml app configuration file generated for mealplanner1 on 2023-08-25T09:26:02-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mealplanner1"
primary_region = "lax"

[build]

[env]
  DJANGO_SETTINGS_MODULE = "mealplanner.settings"

[deploy]
  release_command = "poetry run python manage.py migrate"

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static"


[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
